// Bot API 10.3 parameter catalog, verified 2026-09-06: https://core.telegram.org/bots/api
// Only the curated MyDuckAI Telegram methods are exposed.
export const TELEGRAM_METHODS = {
  admin: {
    banChatMember: {
      chat_id: { type: 'Integer or String', required: true },
      user_id: { type: 'Integer', required: true },
      until_date: { type: 'Integer', required: false },
      revoke_messages: { type: 'Boolean', required: false },
    },
    unbanChatMember: {
      chat_id: { type: 'Integer or String', required: true },
      user_id: { type: 'Integer', required: true },
      only_if_banned: { type: 'Boolean', required: false },
    },
    deleteMessage: {
      chat_id: { type: 'Integer or String', required: true },
      message_id: { type: 'Integer', required: true },
    },
    getChatMember: {
      chat_id: { type: 'Integer or String', required: true },
      user_id: { type: 'Integer', required: true },
    },
    getChatAdministrators: {
      chat_id: { type: 'Integer or String', required: true },
      return_bots: { type: 'Boolean', required: false },
    },
    getChat: { chat_id: { type: 'Integer or String', required: true } },
    pinChatMessage: {
      business_connection_id: { type: 'String', required: false },
      chat_id: { type: 'Integer or String', required: true },
      message_id: { type: 'Integer', required: true },
      disable_notification: { type: 'Boolean', required: false },
    },
    unpinChatMessage: {
      business_connection_id: { type: 'String', required: false },
      chat_id: { type: 'Integer or String', required: true },
      message_id: { type: 'Integer', required: false },
    },
    setChatTitle: {
      chat_id: { type: 'Integer or String', required: true },
      title: { type: 'String', required: true },
    },
    setChatDescription: {
      chat_id: { type: 'Integer or String', required: true },
      description: { type: 'String', required: false },
    },
    createChatInviteLink: {
      chat_id: { type: 'Integer or String', required: true },
      name: { type: 'String', required: false },
      expire_date: { type: 'Integer', required: false },
      member_limit: { type: 'Integer', required: false },
      creates_join_request: { type: 'Boolean', required: false },
    },
    revokeChatInviteLink: {
      chat_id: { type: 'Integer or String', required: true },
      invite_link: { type: 'String', required: true },
    },
  },
  business: {
    getBusinessConnection: { business_connection_id: { type: 'String', required: true } },
    sendMessage: {
      business_connection_id: { type: 'String', required: false },
      chat_id: { type: 'Integer or String', required: true },
      message_thread_id: { type: 'Integer', required: false },
      direct_messages_topic_id: { type: 'Integer', required: false },
      ephemeral_message_parameters: { type: 'EphemeralMessageParameters', required: false },
      text: { type: 'String', required: true },
      parse_mode: { type: 'String', required: false },
      entities: { type: 'Array of MessageEntity', required: false },
      link_preview_options: { type: 'LinkPreviewOptions', required: false },
      disable_notification: { type: 'Boolean', required: false },
      protect_content: { type: 'Boolean', required: false },
      allow_paid_broadcast: { type: 'Boolean', required: false },
      message_effect_id: { type: 'String', required: false },
      suggested_post_parameters: { type: 'SuggestedPostParameters', required: false },
      reply_parameters: { type: 'ReplyParameters', required: false },
      reply_markup: {
        type: 'InlineKeyboardMarkup or ReplyKeyboardMarkup or ReplyKeyboardRemove or ForceReply',
        required: false,
      },
    },
    sendPhoto: {
      business_connection_id: { type: 'String', required: false },
      chat_id: { type: 'Integer or String', required: true },
      message_thread_id: { type: 'Integer', required: false },
      direct_messages_topic_id: { type: 'Integer', required: false },
      ephemeral_message_parameters: { type: 'EphemeralMessageParameters', required: false },
      photo: { type: 'InputFile or String', required: true },
      caption: { type: 'String', required: false },
      parse_mode: { type: 'String', required: false },
      caption_entities: { type: 'Array of MessageEntity', required: false },
      show_caption_above_media: { type: 'Boolean', required: false },
      has_spoiler: { type: 'Boolean', required: false },
      disable_notification: { type: 'Boolean', required: false },
      protect_content: { type: 'Boolean', required: false },
      allow_paid_broadcast: { type: 'Boolean', required: false },
      message_effect_id: { type: 'String', required: false },
      suggested_post_parameters: { type: 'SuggestedPostParameters', required: false },
      reply_parameters: { type: 'ReplyParameters', required: false },
      reply_markup: {
        type: 'InlineKeyboardMarkup or ReplyKeyboardMarkup or ReplyKeyboardRemove or ForceReply',
        required: false,
      },
    },
    sendVideo: {
      business_connection_id: { type: 'String', required: false },
      chat_id: { type: 'Integer or String', required: true },
      message_thread_id: { type: 'Integer', required: false },
      direct_messages_topic_id: { type: 'Integer', required: false },
      ephemeral_message_parameters: { type: 'EphemeralMessageParameters', required: false },
      video: { type: 'InputFile or String', required: true },
      duration: { type: 'Integer', required: false },
      width: { type: 'Integer', required: false },
      height: { type: 'Integer', required: false },
      thumbnail: { type: 'InputFile or String', required: false },
      cover: { type: 'InputFile or String', required: false },
      start_timestamp: { type: 'Integer', required: false },
      caption: { type: 'String', required: false },
      parse_mode: { type: 'String', required: false },
      caption_entities: { type: 'Array of MessageEntity', required: false },
      show_caption_above_media: { type: 'Boolean', required: false },
      has_spoiler: { type: 'Boolean', required: false },
      supports_streaming: { type: 'Boolean', required: false },
      disable_notification: { type: 'Boolean', required: false },
      protect_content: { type: 'Boolean', required: false },
      allow_paid_broadcast: { type: 'Boolean', required: false },
      message_effect_id: { type: 'String', required: false },
      suggested_post_parameters: { type: 'SuggestedPostParameters', required: false },
      reply_parameters: { type: 'ReplyParameters', required: false },
      reply_markup: {
        type: 'InlineKeyboardMarkup or ReplyKeyboardMarkup or ReplyKeyboardRemove or ForceReply',
        required: false,
      },
    },
    sendAudio: {
      business_connection_id: { type: 'String', required: false },
      chat_id: { type: 'Integer or String', required: true },
      message_thread_id: { type: 'Integer', required: false },
      direct_messages_topic_id: { type: 'Integer', required: false },
      ephemeral_message_parameters: { type: 'EphemeralMessageParameters', required: false },
      audio: { type: 'InputFile or String', required: true },
      caption: { type: 'String', required: false },
      parse_mode: { type: 'String', required: false },
      caption_entities: { type: 'Array of MessageEntity', required: false },
      duration: { type: 'Integer', required: false },
      performer: { type: 'String', required: false },
      title: { type: 'String', required: false },
      thumbnail: { type: 'InputFile or String', required: false },
      disable_notification: { type: 'Boolean', required: false },
      protect_content: { type: 'Boolean', required: false },
      allow_paid_broadcast: { type: 'Boolean', required: false },
      message_effect_id: { type: 'String', required: false },
      suggested_post_parameters: { type: 'SuggestedPostParameters', required: false },
      reply_parameters: { type: 'ReplyParameters', required: false },
      reply_markup: {
        type: 'InlineKeyboardMarkup or ReplyKeyboardMarkup or ReplyKeyboardRemove or ForceReply',
        required: false,
      },
    },
    sendDocument: {
      business_connection_id: { type: 'String', required: false },
      chat_id: { type: 'Integer or String', required: true },
      message_thread_id: { type: 'Integer', required: false },
      direct_messages_topic_id: { type: 'Integer', required: false },
      ephemeral_message_parameters: { type: 'EphemeralMessageParameters', required: false },
      document: { type: 'InputFile or String', required: true },
      thumbnail: { type: 'InputFile or String', required: false },
      caption: { type: 'String', required: false },
      parse_mode: { type: 'String', required: false },
      caption_entities: { type: 'Array of MessageEntity', required: false },
      disable_content_type_detection: { type: 'Boolean', required: false },
      disable_notification: { type: 'Boolean', required: false },
      protect_content: { type: 'Boolean', required: false },
      allow_paid_broadcast: { type: 'Boolean', required: false },
      message_effect_id: { type: 'String', required: false },
      suggested_post_parameters: { type: 'SuggestedPostParameters', required: false },
      reply_parameters: { type: 'ReplyParameters', required: false },
      reply_markup: {
        type: 'InlineKeyboardMarkup or ReplyKeyboardMarkup or ReplyKeyboardRemove or ForceReply',
        required: false,
      },
    },
    sendAnimation: {
      business_connection_id: { type: 'String', required: false },
      chat_id: { type: 'Integer or String', required: true },
      message_thread_id: { type: 'Integer', required: false },
      direct_messages_topic_id: { type: 'Integer', required: false },
      ephemeral_message_parameters: { type: 'EphemeralMessageParameters', required: false },
      animation: { type: 'InputFile or String', required: true },
      duration: { type: 'Integer', required: false },
      width: { type: 'Integer', required: false },
      height: { type: 'Integer', required: false },
      thumbnail: { type: 'InputFile or String', required: false },
      caption: { type: 'String', required: false },
      parse_mode: { type: 'String', required: false },
      caption_entities: { type: 'Array of MessageEntity', required: false },
      show_caption_above_media: { type: 'Boolean', required: false },
      has_spoiler: { type: 'Boolean', required: false },
      disable_notification: { type: 'Boolean', required: false },
      protect_content: { type: 'Boolean', required: false },
      allow_paid_broadcast: { type: 'Boolean', required: false },
      message_effect_id: { type: 'String', required: false },
      suggested_post_parameters: { type: 'SuggestedPostParameters', required: false },
      reply_parameters: { type: 'ReplyParameters', required: false },
      reply_markup: {
        type: 'InlineKeyboardMarkup or ReplyKeyboardMarkup or ReplyKeyboardRemove or ForceReply',
        required: false,
      },
    },
    sendVoice: {
      business_connection_id: { type: 'String', required: false },
      chat_id: { type: 'Integer or String', required: true },
      message_thread_id: { type: 'Integer', required: false },
      direct_messages_topic_id: { type: 'Integer', required: false },
      ephemeral_message_parameters: { type: 'EphemeralMessageParameters', required: false },
      voice: { type: 'InputFile or String', required: true },
      caption: { type: 'String', required: false },
      parse_mode: { type: 'String', required: false },
      caption_entities: { type: 'Array of MessageEntity', required: false },
      duration: { type: 'Integer', required: false },
      disable_notification: { type: 'Boolean', required: false },
      protect_content: { type: 'Boolean', required: false },
      allow_paid_broadcast: { type: 'Boolean', required: false },
      message_effect_id: { type: 'String', required: false },
      suggested_post_parameters: { type: 'SuggestedPostParameters', required: false },
      reply_parameters: { type: 'ReplyParameters', required: false },
      reply_markup: {
        type: 'InlineKeyboardMarkup or ReplyKeyboardMarkup or ReplyKeyboardRemove or ForceReply',
        required: false,
      },
    },
    sendVideoNote: {
      business_connection_id: { type: 'String', required: false },
      chat_id: { type: 'Integer or String', required: true },
      message_thread_id: { type: 'Integer', required: false },
      direct_messages_topic_id: { type: 'Integer', required: false },
      ephemeral_message_parameters: { type: 'EphemeralMessageParameters', required: false },
      video_note: { type: 'InputFile or String', required: true },
      duration: { type: 'Integer', required: false },
      length: { type: 'Integer', required: false },
      thumbnail: { type: 'InputFile or String', required: false },
      disable_notification: { type: 'Boolean', required: false },
      protect_content: { type: 'Boolean', required: false },
      allow_paid_broadcast: { type: 'Boolean', required: false },
      message_effect_id: { type: 'String', required: false },
      suggested_post_parameters: { type: 'SuggestedPostParameters', required: false },
      reply_parameters: { type: 'ReplyParameters', required: false },
      reply_markup: {
        type: 'InlineKeyboardMarkup or ReplyKeyboardMarkup or ReplyKeyboardRemove or ForceReply',
        required: false,
      },
    },
    sendMediaGroup: {
      business_connection_id: { type: 'String', required: false },
      chat_id: { type: 'Integer or String', required: true },
      message_thread_id: { type: 'Integer', required: false },
      direct_messages_topic_id: { type: 'Integer', required: false },
      media: {
        type: 'Array of InputMediaAudio, InputMediaDocument, InputMediaLivePhoto, InputMediaPhoto and InputMediaVideo',
        required: true,
      },
      disable_notification: { type: 'Boolean', required: false },
      protect_content: { type: 'Boolean', required: false },
      allow_paid_broadcast: { type: 'Boolean', required: false },
      message_effect_id: { type: 'String', required: false },
      reply_parameters: { type: 'ReplyParameters', required: false },
    },
    sendLocation: {
      business_connection_id: { type: 'String', required: false },
      chat_id: { type: 'Integer or String', required: true },
      message_thread_id: { type: 'Integer', required: false },
      direct_messages_topic_id: { type: 'Integer', required: false },
      ephemeral_message_parameters: { type: 'EphemeralMessageParameters', required: false },
      latitude: { type: 'Float', required: true },
      longitude: { type: 'Float', required: true },
      horizontal_accuracy: { type: 'Float', required: false },
      live_period: { type: 'Integer', required: false },
      heading: { type: 'Integer', required: false },
      proximity_alert_radius: { type: 'Integer', required: false },
      disable_notification: { type: 'Boolean', required: false },
      protect_content: { type: 'Boolean', required: false },
      allow_paid_broadcast: { type: 'Boolean', required: false },
      message_effect_id: { type: 'String', required: false },
      suggested_post_parameters: { type: 'SuggestedPostParameters', required: false },
      reply_parameters: { type: 'ReplyParameters', required: false },
      reply_markup: {
        type: 'InlineKeyboardMarkup or ReplyKeyboardMarkup or ReplyKeyboardRemove or ForceReply',
        required: false,
      },
    },
    sendVenue: {
      business_connection_id: { type: 'String', required: false },
      chat_id: { type: 'Integer or String', required: true },
      message_thread_id: { type: 'Integer', required: false },
      direct_messages_topic_id: { type: 'Integer', required: false },
      ephemeral_message_parameters: { type: 'EphemeralMessageParameters', required: false },
      latitude: { type: 'Float', required: true },
      longitude: { type: 'Float', required: true },
      title: { type: 'String', required: true },
      address: { type: 'String', required: true },
      foursquare_id: { type: 'String', required: false },
      foursquare_type: { type: 'String', required: false },
      google_place_id: { type: 'String', required: false },
      google_place_type: { type: 'String', required: false },
      disable_notification: { type: 'Boolean', required: false },
      protect_content: { type: 'Boolean', required: false },
      allow_paid_broadcast: { type: 'Boolean', required: false },
      message_effect_id: { type: 'String', required: false },
      suggested_post_parameters: { type: 'SuggestedPostParameters', required: false },
      reply_parameters: { type: 'ReplyParameters', required: false },
      reply_markup: {
        type: 'InlineKeyboardMarkup or ReplyKeyboardMarkup or ReplyKeyboardRemove or ForceReply',
        required: false,
      },
    },
    sendContact: {
      business_connection_id: { type: 'String', required: false },
      chat_id: { type: 'Integer or String', required: true },
      message_thread_id: { type: 'Integer', required: false },
      direct_messages_topic_id: { type: 'Integer', required: false },
      ephemeral_message_parameters: { type: 'EphemeralMessageParameters', required: false },
      phone_number: { type: 'String', required: true },
      first_name: { type: 'String', required: true },
      last_name: { type: 'String', required: false },
      vcard: { type: 'String', required: false },
      disable_notification: { type: 'Boolean', required: false },
      protect_content: { type: 'Boolean', required: false },
      allow_paid_broadcast: { type: 'Boolean', required: false },
      message_effect_id: { type: 'String', required: false },
      suggested_post_parameters: { type: 'SuggestedPostParameters', required: false },
      reply_parameters: { type: 'ReplyParameters', required: false },
      reply_markup: {
        type: 'InlineKeyboardMarkup or ReplyKeyboardMarkup or ReplyKeyboardRemove or ForceReply',
        required: false,
      },
    },
    sendPoll: {
      business_connection_id: { type: 'String', required: false },
      chat_id: { type: 'Integer or String', required: true },
      message_thread_id: { type: 'Integer', required: false },
      question: { type: 'String', required: true },
      question_parse_mode: { type: 'String', required: false },
      question_entities: { type: 'Array of MessageEntity', required: false },
      options: { type: 'Array of InputPollOption', required: true },
      is_anonymous: { type: 'Boolean', required: false },
      type: { type: 'String', required: false },
      allows_multiple_answers: { type: 'Boolean', required: false },
      allows_revoting: { type: 'Boolean', required: false },
      shuffle_options: { type: 'Boolean', required: false },
      allow_adding_options: { type: 'Boolean', required: false },
      hide_results_until_closes: { type: 'Boolean', required: false },
      members_only: { type: 'Boolean', required: false },
      country_codes: { type: 'Array of String', required: false },
      correct_option_ids: { type: 'Array of Integer', required: false },
      explanation: { type: 'String', required: false },
      explanation_parse_mode: { type: 'String', required: false },
      explanation_entities: { type: 'Array of MessageEntity', required: false },
      explanation_media: { type: 'InputPollMedia', required: false },
      open_period: { type: 'Integer', required: false },
      close_date: { type: 'Integer', required: false },
      is_closed: { type: 'Boolean', required: false },
      description: { type: 'String', required: false },
      description_parse_mode: { type: 'String', required: false },
      description_entities: { type: 'Array of MessageEntity', required: false },
      media: { type: 'InputPollMedia', required: false },
      disable_notification: { type: 'Boolean', required: false },
      protect_content: { type: 'Boolean', required: false },
      allow_paid_broadcast: { type: 'Boolean', required: false },
      message_effect_id: { type: 'String', required: false },
      reply_parameters: { type: 'ReplyParameters', required: false },
      reply_markup: {
        type: 'InlineKeyboardMarkup or ReplyKeyboardMarkup or ReplyKeyboardRemove or ForceReply',
        required: false,
      },
    },
    sendDice: {
      business_connection_id: { type: 'String', required: false },
      chat_id: { type: 'Integer or String', required: true },
      message_thread_id: { type: 'Integer', required: false },
      direct_messages_topic_id: { type: 'Integer', required: false },
      emoji: { type: 'String', required: false },
      disable_notification: { type: 'Boolean', required: false },
      protect_content: { type: 'Boolean', required: false },
      allow_paid_broadcast: { type: 'Boolean', required: false },
      message_effect_id: { type: 'String', required: false },
      suggested_post_parameters: { type: 'SuggestedPostParameters', required: false },
      reply_parameters: { type: 'ReplyParameters', required: false },
      reply_markup: {
        type: 'InlineKeyboardMarkup or ReplyKeyboardMarkup or ReplyKeyboardRemove or ForceReply',
        required: false,
      },
    },
    sendChatAction: {
      business_connection_id: { type: 'String', required: false },
      chat_id: { type: 'Integer or String', required: true },
      message_thread_id: { type: 'Integer', required: false },
      action: { type: 'String', required: true },
    },
    editMessageText: {
      business_connection_id: { type: 'String', required: false },
      chat_id: { type: 'Integer or String', required: false },
      message_id: { type: 'Integer', required: false },
      inline_message_id: { type: 'String', required: false },
      text: { type: 'String', required: false },
      parse_mode: { type: 'String', required: false },
      entities: { type: 'Array of MessageEntity', required: false },
      link_preview_options: { type: 'LinkPreviewOptions', required: false },
      rich_message: { type: 'InputRichMessage', required: false },
      reply_markup: { type: 'InlineKeyboardMarkup', required: false },
    },
    editMessageCaption: {
      business_connection_id: { type: 'String', required: false },
      chat_id: { type: 'Integer or String', required: false },
      message_id: { type: 'Integer', required: false },
      inline_message_id: { type: 'String', required: false },
      caption: { type: 'String', required: false },
      parse_mode: { type: 'String', required: false },
      caption_entities: { type: 'Array of MessageEntity', required: false },
      show_caption_above_media: { type: 'Boolean', required: false },
      reply_markup: { type: 'InlineKeyboardMarkup', required: false },
    },
    editMessageMedia: {
      business_connection_id: { type: 'String', required: false },
      chat_id: { type: 'Integer or String', required: false },
      message_id: { type: 'Integer', required: false },
      inline_message_id: { type: 'String', required: false },
      media: { type: 'InputMedia', required: true },
      reply_markup: { type: 'InlineKeyboardMarkup', required: false },
    },
    editMessageLiveLocation: {
      business_connection_id: { type: 'String', required: false },
      chat_id: { type: 'Integer or String', required: false },
      message_id: { type: 'Integer', required: false },
      inline_message_id: { type: 'String', required: false },
      latitude: { type: 'Float', required: true },
      longitude: { type: 'Float', required: true },
      live_period: { type: 'Integer', required: false },
      horizontal_accuracy: { type: 'Float', required: false },
      heading: { type: 'Integer', required: false },
      proximity_alert_radius: { type: 'Integer', required: false },
      reply_markup: { type: 'InlineKeyboardMarkup', required: false },
    },
    stopMessageLiveLocation: {
      business_connection_id: { type: 'String', required: false },
      chat_id: { type: 'Integer or String', required: false },
      message_id: { type: 'Integer', required: false },
      inline_message_id: { type: 'String', required: false },
      reply_markup: { type: 'InlineKeyboardMarkup', required: false },
    },
    editMessageReplyMarkup: {
      business_connection_id: { type: 'String', required: false },
      chat_id: { type: 'Integer or String', required: false },
      message_id: { type: 'Integer', required: false },
      inline_message_id: { type: 'String', required: false },
      reply_markup: { type: 'InlineKeyboardMarkup', required: false },
    },
    readBusinessMessage: {
      business_connection_id: { type: 'String', required: true },
      chat_id: { type: 'Integer', required: true },
      message_id: { type: 'Integer', required: true },
    },
    deleteBusinessMessages: {
      business_connection_id: { type: 'String', required: true },
      message_ids: { type: 'Array of Integer', required: true },
    },
    setBusinessAccountName: {
      business_connection_id: { type: 'String', required: true },
      first_name: { type: 'String', required: true },
      last_name: { type: 'String', required: false },
    },
    setBusinessAccountUsername: {
      business_connection_id: { type: 'String', required: true },
      username: { type: 'String', required: false },
    },
    setBusinessAccountBio: {
      business_connection_id: { type: 'String', required: true },
      bio: { type: 'String', required: false },
    },
    setBusinessAccountProfilePhoto: {
      business_connection_id: { type: 'String', required: true },
      photo: { type: 'InputProfilePhoto', required: true },
      is_public: { type: 'Boolean', required: false },
    },
    removeBusinessAccountProfilePhoto: {
      business_connection_id: { type: 'String', required: true },
      is_public: { type: 'Boolean', required: false },
    },
    setBusinessAccountGiftSettings: {
      business_connection_id: { type: 'String', required: true },
      show_gift_button: { type: 'Boolean', required: true },
      accepted_gift_types: { type: 'AcceptedGiftTypes', required: true },
    },
    getBusinessAccountStarBalance: { business_connection_id: { type: 'String', required: true } },
    transferBusinessAccountStars: {
      business_connection_id: { type: 'String', required: true },
      star_count: { type: 'Integer', required: true },
    },
    getBusinessAccountGifts: {
      business_connection_id: { type: 'String', required: true },
      exclude_unsaved: { type: 'Boolean', required: false },
      exclude_saved: { type: 'Boolean', required: false },
      exclude_unlimited: { type: 'Boolean', required: false },
      exclude_limited_upgradable: { type: 'Boolean', required: false },
      exclude_limited_non_upgradable: { type: 'Boolean', required: false },
      exclude_unique: { type: 'Boolean', required: false },
      exclude_from_blockchain: { type: 'Boolean', required: false },
      sort_by_price: { type: 'Boolean', required: false },
      offset: { type: 'String', required: false },
      limit: { type: 'Integer', required: false },
    },
    convertGiftToStars: {
      business_connection_id: { type: 'String', required: true },
      owned_gift_id: { type: 'String', required: true },
    },
    upgradeGift: {
      business_connection_id: { type: 'String', required: true },
      owned_gift_id: { type: 'String', required: true },
      keep_original_details: { type: 'Boolean', required: false },
      star_count: { type: 'Integer', required: false },
    },
    transferGift: {
      business_connection_id: { type: 'String', required: true },
      owned_gift_id: { type: 'String', required: true },
      new_owner_chat_id: { type: 'Integer', required: true },
      star_count: { type: 'Integer', required: false },
    },
    postStory: {
      business_connection_id: { type: 'String', required: true },
      content: { type: 'InputStoryContent', required: true },
      active_period: { type: 'Integer', required: true },
      caption: { type: 'String', required: false },
      parse_mode: { type: 'String', required: false },
      caption_entities: { type: 'Array of MessageEntity', required: false },
      areas: { type: 'Array of StoryArea', required: false },
      post_to_chat_page: { type: 'Boolean', required: false },
      protect_content: { type: 'Boolean', required: false },
    },
    editStory: {
      business_connection_id: { type: 'String', required: true },
      story_id: { type: 'Integer', required: true },
      content: { type: 'InputStoryContent', required: true },
      caption: { type: 'String', required: false },
      parse_mode: { type: 'String', required: false },
      caption_entities: { type: 'Array of MessageEntity', required: false },
      areas: { type: 'Array of StoryArea', required: false },
    },
    deleteStory: {
      business_connection_id: { type: 'String', required: true },
      story_id: { type: 'Integer', required: true },
    },
    repostStory: {
      business_connection_id: { type: 'String', required: true },
      from_chat_id: { type: 'Integer', required: true },
      from_story_id: { type: 'Integer', required: true },
      active_period: { type: 'Integer', required: true },
      post_to_chat_page: { type: 'Boolean', required: false },
      protect_content: { type: 'Boolean', required: false },
    },
  },
  gifts: {
    getAvailableGifts: {},
    getUserGifts: {
      user_id: { type: 'Integer', required: true },
      exclude_unlimited: { type: 'Boolean', required: false },
      exclude_limited_upgradable: { type: 'Boolean', required: false },
      exclude_limited_non_upgradable: { type: 'Boolean', required: false },
      exclude_from_blockchain: { type: 'Boolean', required: false },
      exclude_unique: { type: 'Boolean', required: false },
      sort_by_price: { type: 'Boolean', required: false },
      offset: { type: 'String', required: false },
      limit: { type: 'Integer', required: false },
    },
    getChatGifts: {
      chat_id: { type: 'Integer or String', required: true },
      exclude_unsaved: { type: 'Boolean', required: false },
      exclude_saved: { type: 'Boolean', required: false },
      exclude_unlimited: { type: 'Boolean', required: false },
      exclude_limited_upgradable: { type: 'Boolean', required: false },
      exclude_limited_non_upgradable: { type: 'Boolean', required: false },
      exclude_from_blockchain: { type: 'Boolean', required: false },
      exclude_unique: { type: 'Boolean', required: false },
      sort_by_price: { type: 'Boolean', required: false },
      offset: { type: 'String', required: false },
      limit: { type: 'Integer', required: false },
    },
    getMyStarBalance: {},
    getStarTransactions: {
      offset: { type: 'Integer', required: false },
      limit: { type: 'Integer', required: false },
    },
    sendGift: {
      user_id: { type: 'Integer', required: false },
      chat_id: { type: 'Integer or String', required: false },
      gift_id: { type: 'String', required: true },
      pay_for_upgrade: { type: 'Boolean', required: false },
      text: { type: 'String', required: false },
      text_parse_mode: { type: 'String', required: false },
      text_entities: { type: 'Array of MessageEntity', required: false },
    },
    giftPremiumSubscription: {
      user_id: { type: 'Integer', required: true },
      month_count: { type: 'Integer', required: true },
      star_count: { type: 'Integer', required: true },
      text: { type: 'String', required: false },
      text_parse_mode: { type: 'String', required: false },
      text_entities: { type: 'Array of MessageEntity', required: false },
    },
    refundStarPayment: {
      user_id: { type: 'Integer', required: true },
      telegram_payment_charge_id: { type: 'String', required: true },
    },
  },
};
